apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-service
spec:
  selector:
    matchLabels:
      app: mysql-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-service
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-setup-cm
                  key: mysql-root-password

            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-setup-cm
                  key: mysql-db

            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-setup-cm
                  key: mysql-db-user

            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-setup-cm
                  key: mysql-db-password

          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    app: mysql-service
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30008
