apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ingress-example

spec:

  rules:

    - host: "foo.bar.com"
      http:
        paths:
          - pathType: Prefix
            path: "/bar"
            backend:
              service:
                name: k8s-service
                port:
                  number: 80

#    - host: "*.foo.com"
#      http:
#        paths:
#          - pathType: Prefix
#            path: "/foo"
#            backend:
#              service:
#                name: k8s-service
#                port:
#                  number: 80