apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8s-deployment
  labels:
    app: k8s-test

spec:
  replicas: 2

  selector:
    matchLabels:
      app: k8s-test

  template:
    metadata:
      labels:
        app: k8s-test

    spec:
      containers:
        - name: k8s-deployment-app
          image: ctli/kubernetes-deploy:v1
          ports:
            - containerPort: 8080