apiVersion: v1
kind: ConfigMap

metadata:
  name: mysql-setup-cm

data:
  mysql-root-password: root
  mysql-db: mydb
  mysql-db-user: guest
  mysql-db-password: guest

---

apiVersion: v1
kind: ConfigMap

metadata:
  name: spring-boot-crud-cm

data:
  db-url: jdbc:mysql://mysql-service:3306/user-service
  db-driver: com.mysql.cj.Driver

